export const experiences = [
  {
    company: "Devioz S.A.C.",
    date: "Enero 2024 - Julio 2024",
    tasks: [
      "Diseño y desarrollo de interfaces de usuario interactivas",
      "Creación de sitios web responsivos y eficientes con Node.js y Express.js",
      "Gestión de bases de datos con PostgreSQL y SQL",
      "Implementación y consumo de APIs RESTful",
      "Mejora de la calidad del código JavaScript con TypeScript",
    ],
    techStack: [
      "Git",
      "GitHub",
      "React",
      "NestJS",
      "Jenkins",
      "Postman",
      "TypeScript",
      "Docker",
      "Google Cloud",
      "AWS",
    ],
  },
  {
    company: "Awcrast",
    date: "Julio 2023 - Octubre 2023",
    tasks: [
      "Diseño de interfaces coherentes con Figma",
      "Desarrollo de aplicaciones móviles con React Native e Ionic",
      "Optimización de rendimiento y gestión de código con Git y GitHub",
      "Compatibilidad con las últimas versiones de React Native",
      "Colaboración con equipos utilizando Postman",
    ],
    techStack: [
      "React Native",
      "Ionic",
      "Postman",
      "Figma",
      "GitHub",
      "Git",
      "SQL",
      "TypeScript",
    ],
  },
];